### ISSUE TITLE
Master UI: look at using dat.gui library

### ISSUE THREAD

**Issue by alfski** [abhishekvp/cesium-lg#27]
Before getting to stuck into UI designs, i suggest using the simple dat.gui for master UI.
dat.gui is a common library for basic html user interfaces and would be fine to use in this project.

https://github.com/dataarts/dat.gui

https://workshop.chromeexperiments.com/examples/gui/

It may be worthwhile looking at syncing dat.gui 'state' from the master to slaves?
Passing the dat structure to slaves when there's a change.

**Comment by alfski** [comment]
The dat.gui code below duplicates some of what is in the standard Cesium UI.
When really we need a way of querying the viewer state from Cesium itself, I'm sure this is possible!

Anyhow for the moment this is workaround...

```
var CesiumState = function() {
 this.Fog = true;
 this.Lighting = false;
 this.Terrain = 'STK';
 this.Imagery = 'Bing Aerial';
 this.KML = './clouds.kml';
 this.ShowFPS = false;
};

window.onload = function() {
        var state = new CesiumState;
        var gui = new dat.GUI();
        gui.domElementId = 'gui';
        gui.add(state, 'Terrain', ['STK', 'Ellipsoid', 'VHK']);
        gui.add(state, 'Imagery', ['Bing Aerial', 'Bing Labels', 'Bing Road', 'Grid', 'Open Street Map', 'Watercolor']);
        gui.add(state, 'KML');
        gui.add(state, 'Fog');
        gui.add(state, 'Lighting');
        gui.add(state, 'ShowFPS');
};
```

**Comment by alfski** [comment]
You CAN get the map base layer from Cesium viewer object.

eg. from browser console directly peaking inside "viewer", with MapBox Street map selected...

```
viewer._baseLayerPicker._viewModel._currentImageryProviders[0].url
"https://api.mapbox.com/v4/"
viewer._baseLayerPicker._viewModel._currentImageryProviders[0]._mapId
"mapbox.streets"
```

switch to Bing Maps with Labels...

```
viewer._baseLayerPicker._viewModel._currentImageryProviders[0].url
"https://dev.virtualearth.net"
viewer._baseLayerPicker._viewModel._currentImageryProviders[0].mapStyle
"AerialWithLabels"
```

Possibly there are standard calls or events to get this information? Check with Cesium forum maybe.

**Comment by abhishekvp** [comment]
We now use dat.gui for all the UI control elements.
