### ISSUE TITLE
clean up git history, repo is huge!!

### ISSUE THREAD

**Issue by alfski** [abhishekvp/cesium-lg#43]
Hi, the git history still contains all the Cesium source.
Making the repo 80Mb in size when it really should be 8Kb :)

Thanks.

**Comment by abhishekvp** [comment]
Done!

**Comment by alfski** [comment]
Are you sure?? A master download is 100Kb, but a git clone in a fresh directory is still 14,000 files and 80Mb!

```
git clone https://github.com/abhishekvp/cesium-lg/
Initialized empty Git repository in /var/www/html/gsoc/cesium-lg/.git/
remote: Counting objects: 14158, done.
remote: Compressing objects: 100% (24/24), done.
```

**Comment by abhishekvp** [comment]
The git clone download was of greater size because it was also downloading the other branch 'andrew' in addition to the 'master'. I have deleted that branch. So the git clone download size now is about 100kb.
